/*
   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/

/* A 5x7 bitmap font for the on-screen face. Kept in the firmware instead of a
 * graphics library: 665 bytes of table against the ~250 kB LVGL would add to an
 * image that already fills most of its 1.92 MB OTA slot. */

#pragma once

#include <stdint.h>

#define FONT5X7_FIRST 0x20 /* space */
#define FONT5X7_LAST 0x7E  /* tilde */
#define FONT5X7_GLYPHS (FONT5X7_LAST - FONT5X7_FIRST + 1)
#define FONT5X7_COLS 5
#define FONT5X7_ROWS 7
/* One blank column and row of tracking, so a glyph cell is 6x8 at scale 1. */
#define FONT5X7_ADVANCE 6
#define FONT5X7_LINE 8

/* Row-major, bit 4 is the leftmost column. Generated by tools/genfont.py. */
extern const uint8_t font5x7[FONT5X7_GLYPHS][FONT5X7_ROWS];
